name: repertoire_contactes
description: Une application mobile pour réunir ses amis dans une communauté.

publish_to: 'none'

version: 1.0.12+13

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  get: ^4.6.5
  fluent_ui: ^3.12.0
  fluentui_system_icons: ^1.1.172
  flutter_screenutil: ^5.5.3+2
  connectivity_plus: ^2.3.4
  shared_preferences: ^2.0.15
  firebase_core: ^1.18.0
  firebase_dynamic_links: ^4.2.6
  firebase_auth: ^3.3.20
  cloud_firestore: ^3.1.18
  firebase_storage: ^10.2.18
  firebase_app_check: ^0.0.6+14
  google_fonts: ^3.0.1
  package_info_plus: ^1.4.2
  flutter_native_contact_picker: ^0.0.3
  intl_phone_field: ^3.1.0
  flutter_svg: ^1.1.0
  crypto: ^3.0.2
  emoji_regex: ^0.0.2
  pinput: ^2.2.11
  share_plus: ^4.0.9
  image_pickers: ^2.0.0+2
  url_launcher: ^6.1.4
  cached_network_image: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons_maker: ^0.10.2

flutter_native_splash:
  color: "#eeeeee"
  image: assets/icons/rc_icon.png
  color_dark: "#2b2b2b"
  image_dark: assets/icons/rc_icon.png
  android: true
  ios: true
  web: true
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/icons/rc_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/icons/
