// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh8FDBFHIoRcxHagd4FphZ0FQWXIuBBTA',
    appId: '1:1068506741826:web:576e0695fc7ec0687701db',
    messagingSenderId: '1068506741826',
    projectId: 'repertoire-contactes',
    authDomain: 'repertoire-contactes.firebaseapp.com',
    storageBucket: 'repertoire-contactes.appspot.com',
    measurementId: 'G-01YPKJY3JE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MRKfTWQnHP7oLFzB6ObqHWGGl74kjS4',
    appId: '1:1068506741826:android:dcd90524a4a7c1117701db',
    messagingSenderId: '1068506741826',
    projectId: 'repertoire-contactes',
    storageBucket: 'repertoire-contactes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQAHMTrevXtzQUydePyxSerMqELwqQVg',
    appId: '1:1068506741826:ios:c1a193869e2455577701db',
    messagingSenderId: '1068506741826',
    projectId: 'repertoire-contactes',
    storageBucket: 'repertoire-contactes.appspot.com',
    androidClientId: '1068506741826-qpf9avtvd099c9t28ip8qdlqd43tjccc.apps.googleusercontent.com',
    iosClientId: '1068506741826-3nkj8ramdu12n0jm33697up7hrqi27vo.apps.googleusercontent.com',
    iosBundleId: 'com.waouhmonde.repertoireContactes',
  );
}
